### ISSUE TITLE
TooManyProviderTokenUpdates

### ISSUE THREAD

**Issue by andrewvmail** [esl/sparrow#50] opened 2021-04-30 21:57 UTC
Hello!

Can we get closing/reopening connection when we see TooManyProviderTokenUpdates. I'm using mongoosepush.

I believe it's related to this issue that's happening here 
https://github.com/jchambers/pushy/issues/811

Currently my fix is to watch the log from outside and restart the process using swatchdog.

I attempted to patch this lib but i don't know enough and it ended up giving me some endless loop...

https://gist.github.com/andrewvmail/d442b7239611a55afd60f4e71166ab2f

Cheers!

**Comment by pawlooss1** [comment] 2024-02-27 13:49
That's really strange. The library is supposed to hold a single authentication token and refresh it every 50 minutes. The [Apple documentation](https://developer.apple.com/documentation/usernotifications/establishing-a-token-based-connection-to-apns#Refresh-your-token-regularly) states that the token should be refreshed between 20 and 60 minutes.
The only reason that comes to my mind right now is that the TokenBearer process died before the 20 minutes time while the connection process is alive. Then the connection process would use a new token (after the TokenBearer is restarted) on the same connection which would trigger the `TooManyProviderTokenUpdates` response. Could you look into logs for messages like `Shutting down TokenBearer`? Also, it would be helpful to turn the debug logs because then the library logs every token refresh with `Updating APNS token` message.
Nevertheless, I don't think that closing/reopening the connection would be the proper way to handle such issue. It'd be only a workaround. We should seek the root cause of this problem and fix it.

**Comment by pawlooss1** [comment] 2024-03-04 08:43
Closing issue. If the problem is still there feel free to reopen.

**Closed by pawlooss1** 2024-03-04 08:43 UTC
